Repository gupta-ritik/ExpenseTracker, pull requests merged in 2024-10, with the labels that each got.

#30 Fixes Application error
  app/(root)/my-banks/page.tsx
Labels: gssoc-ext, level2

#37 ADDED USER TO USER TRANSFER
  app/api/transfer.ts
  lib/actions/transferFunds.actions.ts
  package-lock.json
  package.json
Labels: gssoc-ext, level1

#54 added the husky
  .husky/pre-commit
  package.json
Labels: gssoc-ext, level1, hacktoberfest-accepted

#67 Create auto-comment-issue.yml
  .github/workflow/auto-comment-issue.yml
Labels: gssoc-ext, level1

#70 Adding backend for login/signup
  .env
  .env.example
  app/api/(auth)/signin/route.ts
  app/api/(auth)/signout/route.ts
  app/api/(auth)/signup/route.ts
  app/api/(auth)/verify/route.ts
  lib/jwt.ts
  lib/mongodb.ts
  package-lock.json
  package.json
Labels: gssoc-ext, level3

#63 Loading bar
  app/api/sentry-example-api/route.ts
  app/api/transfer.ts
  app/layout.tsx
  app/page.tsx
  app/root/layout.tsx
  app/root/my-banks/page.tsx
  app/root/page.tsx
  app/root/payment-transfer/page.tsx
  app/root/transaction-history/page.tsx
  components/SideBar.tsx
  constants/index.ts
  lib/actions/transferFunds.actions.ts
  middleware.ts
  package-lock.json
  package.json
  pnpm-lock.yaml
  types/index.d.ts
Labels: gssoc-ext, level2

#100 updated readme
  README.md
Labels: gssoc-ext, level1
